theme: jekyll-theme-cayman
title: Iznajmljivanje automobila
description: Logate Akademija - Web developer (2020), završni projekat

github:
  repository_url_2: https://github.com/bolo-med/iznajmljivanje_automobila
